=== AmarMaharjan-hub/Java-2-assignments/JavaWeb/build/web/WEB-INF/classes/xmlFiles/customer.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->
<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT customer (firstname|lastname|age|ssn|address)*>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT ssn (#PCDATA)>
<!ELEMENT address (addressline1|city|state|country)*>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!--<!ATTLIST __ROOT__ version CDATA #REQUIRED>-->

=== AmarMaharjan-hub/Java-2-assignments/JavaWeb/build/web/WEB-INF/classes/xmlFiles/customer.xml
<?xml version="1.0"?>
<!DOCTYPE customer SYSTEM "customer.dtd">
<!--<?xml version="1.0" encoding="UTF-8"?>-->
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<customer>
    <firstname>John</firstname>
    <lastname>Smith</lastname>
    <age>20</age>
    <ssn>23324</ssn>
    <address>
        <addressline1>Apt2222</addressline1>
        <city>Columbus</city>
        <state>OH</state>
        <country>USA</country>
    </address>
</customer>
